databases:
  - name: musicalsite_DB
    databaseName: musicalsite_db
    user: musicalsite
    region: singapore

services:
  - type: web
    name: musicalsite
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musicalsite_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false